### ISSUE TITLE
Question about logging each file separatly and PRE_EXECUTE event

### ISSUE THREAD

**Issue by Fafacraft** [le-phare/import-bundle#17]
Hi,

I am trying to import multiple files in one table, using the loop:true option for loading files in the temporary table first.
However, I would like to still have each file be logged independently, for example to know which file had an issue if there is an exception. Is this possible with the VALIDATE_SOURCE event ?

Also, what is the intended purpose of the PRE_EXECUTE event ? Could you give some exemples about what "Additional functionality" should be hooked to the event ? 

Thanks,
Fabien.

**Comment by thislg** [comment]
Hello,

About VALIDATE_SOURCE event: it is issued before loading each file so you could use it to validate each file before load (meaning you have to iterate over the file yourself). After data is loaded in the temporary table, you can use the file_line_no column to know which file the line comes from.

About PRE_EXECUTE event: you can add anything you need to run early in the import process. Example usage can be logging the import start or downloading files from an external source to import them.
